
services:
  todolist_app:
    container_name: todolist_app
    image: pee-java-app:todolist-1.0.0
    build: .
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://todolist_db:5432/todolist
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - todolist_db
    volumes:
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvm spring-boot:run

  todolist_db:
    container_name: todolist_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    volumes:
      - todolist_postgres_data:/var/lib/postgresql/data

volumes:
    todolist_postgres_data: